name: svgaplayer_flutter
description: The SVGAPlayer implementation of Flutter using CustomPainter.
version: 2.1.2
homepage: https://github.com/yyued/SVGAPlayer-Flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^2.0.0
  http: ^0.13.3
  path_drawing: ^1.0.0
  archive: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
